### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-maria-badanina#1]
Awesome job @maria-badanina !!

What about improving it? Here you have some tips:

- [x] Add a README, a .gitignore and a LICENSE
- [x] Remove file system related files 
- [x] Menu items should be links
- [x] Remove uppercase words from HTML (BLOG -> Blog), and give it styles from CSS.
- [x] Remove `br` tags, they do not add value to content and we can do the same using CSS.
- [x] Improve hierarchy adding more styles to `body` tag as font-size, font-weight, color, background-color.

Here you have a little challenge, let's imagine that you could not use position and transform on `.text` selector. Do you know any alternatives to center the text?

Feel free to add your mini reset and the box model with the star selector ;)

**Comment by maria-badanina** [comment]
Thanks for you feedback @nasivuela ☺️
I think I fixed everything by your list and I positioned the text using flex-box properties for parent container: display: flex; align-items: center; justify-content: center; and I also gave it height: 100%; width: 100%; and now the text is centered horizontally and vertically 😊

**Comment by nasivuela** [comment]
Ole!

Two more improvements:

- [ ] Improve the title of the page, it shouldn't be about you or the evaluation but about the page, something like 'Adalab' could work ;)
- [ ] We have an empty link! That will be a problem for accessibility, we can fix it removing the logo image from CSS and adding it to HTML with an alternative text

Go for it!

**Comment by maria-badanina** [comment]
Done! 😊

**Comment by nasivuela** [comment]
You got it!

![](https://media.giphy.com/media/9u2VMjryaRD4Wtuwws/giphy.gif)
